#!/bin/sh

# Copyright (c) 2013-2017, The PurpleI2P Project
#
# This file is part of Purple i2pd project and licensed under BSD3
#
# See full license text in LICENSE file at top of project tree

screenfind=$(which screen)
if [ -z $screenfind ]; then
		echo "Can't find 'screen' installed. That script needs it!";
		exit 1;
fi

screen -Adm -S i2pd ./i2pd-osx --datadir=.
