#!/bin/sh

# Copyright (c) 2013-2017, The PurpleI2P Project
#
# This file is part of Purple i2pd project and licensed under BSD3
#
# See full license text in LICENSE file at top of project tree

arch=$(uname -m)

if [ $arch == "x86_64" ]
	screen -Adm -S i2pd ./i2pd-x86_64 --datadir=.
else
	screen -Adm -S i2pd ./i2pd-i386 --datadir=.
fi


